apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
  labels:
{{- include "rememberthis.v1.backend-pod-labels" . | indent 4 }}
spec:
  ports:
    - port: 8080
  selector: 
{{- include "rememberthis.v1.backend-pod-labels" . | indent 6 }}