apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: {{ .Values.namespace }}
spec: 
  selector: 
{{- include "rememberthis.v1.database-pod-labels" . | indent 4 }}
  ports: 
    - port: 3306
      targetPort: 3306
      protocol: TCP
  
