apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mysql
  namespace: remember-this
  labels:    
    app: "remember-this"
    tier: "database"
spec: 
  serviceName: "mysql"
  replicas: 1
  selector: 
    matchLabels:      
      app: "remember-this"
      tier: "database"
  template: 
    metadata: 
      labels:        
        app: "remember-this"
        tier: "database"
    spec:      
      containers:
        - name: mysql
          image: "willey599/mysql:1.1"
          ports: 
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom: 
                secretKeyRef:
                  name: secrets
                  key: mysql-database-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: mysql-password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata: 
        name: mysql-data
      spec: 
        accessModes: [ "ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi